name: tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t eznode-test .

    - name: Run tests
      run: ./test.sh eznode-test